// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type OperationType string

const (
	OperationTypeDeposit    OperationType = "deposit"
	OperationTypeWithdrawal OperationType = "withdrawal"
	OperationTypeTransfer   OperationType = "transfer"
)

func (e *OperationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OperationType(s)
	case string:
		*e = OperationType(s)
	default:
		return fmt.Errorf("unsupported scan type for OperationType: %T", src)
	}
	return nil
}

type NullOperationType struct {
	OperationType OperationType
	Valid         bool // Valid is true if OperationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOperationType) Scan(value interface{}) error {
	if value == nil {
		ns.OperationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OperationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOperationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OperationType), nil
}

type Account struct {
	ID        pgtype.UUID
	Name      string
	Balance   string
	Currency  string
	IsSystem  bool
	CreatedAt pgtype.Timestamptz
}

type Entry struct {
	ID            pgtype.UUID
	AccountID     pgtype.UUID
	Debit         string
	Credit        string
	TransactionID pgtype.UUID
	OperationType string
	Description   pgtype.Text
	CreatedAt     pgtype.Timestamptz
}
