// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (
    account_id, debit, credit, transaction_id, operation_type, description
) VALUES (
    $1, CAST($2 AS NUMERIC(19,4)), CAST($3 AS NUMERIC(19,4)), $4, $5, $6
)
RETURNING id, account_id, debit, credit, transaction_id, operation_type, description, created_at
`

type CreateEntryParams struct {
	AccountID     pgtype.UUID
	Column2       string
	Column3       string
	TransactionID pgtype.UUID
	OperationType string
	Description   pgtype.Text
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, createEntry,
		arg.AccountID,
		arg.Column2,
		arg.Column3,
		arg.TransactionID,
		arg.OperationType,
		arg.Description,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Debit,
		&i.Credit,
		&i.TransactionID,
		&i.OperationType,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, balance, currency, is_system, created_at FROM accounts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAccount(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Balance,
		&i.Currency,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountBalance = `-- name: GetAccountBalance :one
SELECT CAST(
    (COALESCE(SUM(credit), 0::NUMERIC) - COALESCE(SUM(debit), 0::NUMERIC))
    AS NUMERIC(19,4)) AS calculated_balance
FROM entries
WHERE account_id = $1
`

func (q *Queries) GetAccountBalance(ctx context.Context, accountID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getAccountBalance, accountID)
	var calculated_balance string
	err := row.Scan(&calculated_balance)
	return calculated_balance, err
}

const getAccountForUpdate = `-- name: GetAccountForUpdate :one
SELECT id, name, balance, currency, is_system, created_at FROM accounts
WHERE id = $1 LIMIT 1
FOR UPDATE
`

func (q *Queries) GetAccountForUpdate(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountForUpdate, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Balance,
		&i.Currency,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const getSettlementAccountForUpdate = `-- name: GetSettlementAccountForUpdate :one
SELECT id, name, balance, currency, is_system, created_at FROM accounts
WHERE is_system = TRUE AND name = 'Settlement Account'
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetSettlementAccountForUpdate(ctx context.Context) (Account, error) {
	row := q.db.QueryRow(ctx, getSettlementAccountForUpdate)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Balance,
		&i.Currency,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const updateAccountBalance = `-- name: UpdateAccountBalance :exec
UPDATE accounts
SET balance = balance + CAST($1 AS NUMERIC(19,4))
WHERE id = $2
`

type UpdateAccountBalanceParams struct {
	Column1 string
	ID      pgtype.UUID
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error {
	_, err := q.db.Exec(ctx, updateAccountBalance, arg.Column1, arg.ID)
	return err
}
